class AccessInfo(object):
    math_g1_student_id = 'math1ko6'
    math_g1_token = 'math1ko'
    physics_g1_student_id ='phys1ko16'
    physics_g1_token = 'phys1ko'
    math_g3_student_id = 'math3ko3'
    math_g3_token = 'math3ko'
    physics_g3_student_id ='phys3ko9'
    physics_g3_token = 'phys3ko'
    random_student_id = 'random2017G3ko2'
    random_token = 'tokenko'
    cr_student_id = 'creac4'
    cr_token = 'creac'
    random_faculty_id = 'GTP'
    random_faculty_token = 'faculty'